### ISSUE TITLE
User Friendly Improvement

### ISSUE THREAD

**Issue by HW-Lee** [HW-Lee/AudioAutoTest#2]
1. FAQ
2. Setup steps (including apk installation and needed files)

**Comment by Rios-Kao** [comment]
1. windows 7/10 setup
	1.1 shell command don't work (below provided by roger)
	    -> win_dumpsys, _ = subprocess.Popen( "powershell.exe \"adb -s {} shell dumpsys window windows | select-string -pattern \"Window #\"\"".format(self.serialno), \ shell=True, stdout=subprocess.PIPE).communicate()
            ->shell 改 power shell
           ->grep 改 select-string
	1.2 host log save path.
	
2. move apk install into readme steps.
   -> It may need to nofity to user open the application and allow permission at first launch.
3. test audio file that pushed by each task scripts.
   -> need modify ssr_test.py

4. apk don't select max volume
   ->remove the setting, and let user adjust volume them need.

**Comment by HW-Lee** [comment]
1. windows 7/10 capability issue should be solved after [the commit](https://github.com/HW-Lee/AudioAutoTest/commit/597682335763df7e26afdc9a5c99168386e2bd3c). Note that the function `push_files` has not supported in win for the difference of the command `find` between linux and win.
2. apk installation will be added in README later.
3. the test audio files are pushed in any case, however it's only supported in linux.
